// this is how you call an instance method

String name = new String("Anya"); // created an instance (1)
name = name.toLowerCase() // anya (2)
  
/**

Built-in methods belong to the Standard Java library. Now there are a lot of built-in methods that convert or compare values, 
round doubles, find the maximum or the minimum value, and do a lot of useful operations. We've already dealt with the round(), 
isLetter(), compareTo(), hasNext() methods, but the number of built-in methods is huge and constantly growing. You can find 
the method you need in the Oracle documentation. For example, check out the link to the Math library.

In contrast to built-in methods, user-defined methods are created by the programmer. It is a common practice 
to create a customized subprogram for a specific purpose. You may create your own method and even put it in 
your own class. Later on, we will learn why it is a good practice to use user-defined methods and how to actually create them. **/
